#!/usr/bin/env python3
"""Lattice weekly check-in automation.

Connects to the user's Chrome session and populates the weekly update
on Lattice with the personal summary generated by the weekly notes agent.

Usage:
  python3 tools/lattice_update.py '<JSON with answers>'

  JSON format:
  {
    "focus": "What I focused on this week...",
    "plans": "Plans and priorities for next week...",
    "challenges": "Challenges or roadblocks...",
    "anything_else": "Anything else on my mind..."
  }

Launches Chrome with a persistent profile so login sessions are preserved.
"""

import argparse
import json
import sys

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
from browser_helper import cleanup, connect_to_chrome

LATTICE_USER_ID = "36390560-010f-4084-a051-dd9ff80450e2"
LATTICE_URL = f"https://66degrees.latticehq.com/users/{LATTICE_USER_ID}/updates"

QUESTION_KEYS = ["focus", "plans", "challenges", "anything_else"]

QUESTION_PATTERNS = [
    "What did you focus on",
    "plans and priorities",
    "challenges or roadblocks",
    "anything else",
]


def _handle_sso_login(page):
    """Click through SSO login if the page redirects to a sign-in prompt."""
    for selector in [
        'a:has-text("Single sign-on")',
        'button:has-text("Single sign-on")',
        'a:has-text("Sign in")',
        'a:has-text("Log in")',
    ]:
        try:
            btn = page.locator(selector).first
            if btn.is_visible(timeout=2000):
                print(f"SSO prompt detected, clicking '{selector}'...", file=sys.stderr)
                btn.click(timeout=5000)
                page.wait_for_timeout(10000)
                print("SSO login completed.", file=sys.stderr)
                return
        except Exception:
            continue


def populate_update(page, answers):
    """Navigate to Lattice and populate the weekly check-in answers."""
    print(f"Navigating to Lattice: {LATTICE_URL}", file=sys.stderr)
    page.goto(LATTICE_URL, wait_until="domcontentloaded", timeout=60000)
    page.wait_for_timeout(5000)

    # Handle SSO login redirect if prompted
    _handle_sso_login(page)

    # Lattice check-in pages have text areas for each question.
    # Strategy: find all visible textareas/contenteditable elements,
    # or match by the question label text.

    filled = 0

    for key, pattern in zip(QUESTION_KEYS, QUESTION_PATTERNS):
        answer = answers.get(key, "").strip()
        if not answer:
            continue

        try:
            # Try to find the question label, then the associated input
            label = page.get_by_text(pattern, exact=False).first
            if label.is_visible(timeout=3000):
                # The input is usually a sibling or nearby element
                parent = label.locator("xpath=ancestor::div[position()<=3]").last
                text_field = parent.locator(
                    "textarea, [contenteditable='true'], "
                    "[role='textbox'], input[type='text']"
                ).first

                if text_field.is_visible(timeout=2000):
                    text_field.click(timeout=2000)
                    page.wait_for_timeout(300)
                    text_field.fill(answer, timeout=3000)
                    filled += 1
                    print(f"Filled '{key}'.", file=sys.stderr)
                    continue
        except Exception as e:
            print(f"Label approach failed for '{key}': {e}", file=sys.stderr)

        # Fallback: try by textarea index order
        try:
            idx = QUESTION_KEYS.index(key)
            textareas = page.locator(
                "textarea:visible, [contenteditable='true']:visible, "
                "[role='textbox']:visible"
            ).all()
            if idx < len(textareas):
                textareas[idx].click(timeout=2000)
                page.wait_for_timeout(300)
                textareas[idx].fill(answer, timeout=3000)
                filled += 1
                print(f"Filled '{key}' via index fallback.", file=sys.stderr)
        except Exception as e:
            print(f"Index fallback failed for '{key}': {e}", file=sys.stderr)

    if filled == 0:
        print("WARNING: Could not fill any fields.", file=sys.stderr)
        print("Page text for debugging:", file=sys.stderr)
        print("---BEGIN_PAGE_TEXT---")
        try:
            print(page.locator("body").inner_text(timeout=5000))
        except Exception:
            print("(could not read page text)")
        print("---END_PAGE_TEXT---")
    else:
        print(f"Filled {filled}/{len(answers)} field(s).", file=sys.stderr)

    page.screenshot(path="/tmp/lattice_update.png")
    print("Screenshot saved to /tmp/lattice_update.png", file=sys.stderr)
    print("LATTICE_DONE")
    print(
        "Please review the update in the browser before submitting.",
        file=sys.stderr,
    )


def main():
    parser = argparse.ArgumentParser(description="Lattice weekly update automation")
    parser.add_argument(
        "answers",
        help=(
            'JSON with answers: {"focus": "...", "plans": "...", '
            '"challenges": "...", "anything_else": "..."}'
        ),
    )
    parser.add_argument(
        "--url",
        default=None,
        help="Override the Lattice check-in URL (e.g. for a different week's checkinId)",
    )
    args = parser.parse_args()

    answers = json.loads(args.answers)

    pw, browser, page = connect_to_chrome()
    try:
        if args.url:
            global LATTICE_URL
            LATTICE_URL = args.url
        populate_update(page, answers)
    finally:
        cleanup(pw, browser)


if __name__ == "__main__":
    main()
